tasks:
  - before: |
      export PATH="$HOME/bin:$PATH"
      echo 'export PATH="$HOME/bin:$PATH"' >> ~/.bashrc
      sudo apt-get update
      sudo apt-get install -q -y libunwind-dev build-essential clang libssl-dev pkg-config
      DFX_VERSION=0.22.0 DFXVM_INIT_YES=true sh -ci "$(curl -fsSL https://internetcomputer.org/install.sh)"
      npm install &
      source "$HOME/.local/share/dfx/env"
      rustup target add wasm32-wasi
      cargo install --git https://github.com/wasm-forge/wasi2ic --rev 806c3558aad24224852a9582f018178402cb3679
      export FOO=$(pwd)
      cd $HOME && git clone https://github.com/demergent-labs/wasmedge-quickjs && cd wasmedge-quickjs && git checkout c21ff69f442998e4cda4619166e23a9bc91418be
      cd $FOO
      mkdir -p ${HOME}/.config/azle
      mv $HOME/wasmedge-quickjs ${HOME}/.config/azle/wasmedge-quickjs_$(npx azle@0.21.1 dockerfile-hash)
      sed -i 's/npx azle backend/npx azle --native-compilation backend/g' dfx.json
      open README.md

vscode:
  extensions:
    - dfinity-foundation.vscode-motoko

ports:
  - name: Replica
    port: 4943
    visibility: public
    onOpen: ignore
  - name: Node
    port: 3000
    visibility: public
    onOpen: open-browser
